services:
  - type: web
    name: naki-wreck-planner
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GOOGLE_API_KEY
        value: AIzaSyB5xtyn4xr6XM-gtEegSm-01kBQZ3YkCak
